spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: siva
    password: siva
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
